### PR TITLE
upgrade to processing 2.1

### PR DESCRIPTION
**Pull request by longbai**
use processing 2.1

### CODE REVIEW

**Comment by rictic** [comment]
Thanks for the pull request.

Ideally we'd use a build system that pulled in requirements dynamically, but this is a good incremental change.

**Comment by dwo** [comment]
Has anyone else seen this change cause an Exception like this?

```
Exception in thread "Animation Thread" java.lang.IllegalAccessError: tried to access field processing.core.PFont.size from class code_swarm
    at code_swarm.drawLegend(code_swarm.java:537)
    at code_swarm.draw(code_swarm.java:426)
    at processing.core.PApplet.handleDraw(PApplet.java:2306)
    at processing.core.PGraphicsJava2D.requestDraw(PGraphicsJava2D.java:243)
    at processing.core.PApplet.run(PApplet.java:2177)
    at java.lang.Thread.run(Thread.java:744)
```

**Comment by longbai** [comment]
@dwo you need update the code_swarm.java, please reference the PR  file code_swarm.java line 537

**Comment by dwo** [comment]
@longbai hey, I was running from `master` with that change on `code_swarm.java`, `getSize()` instead of `size`, right? I could open a separate issue.

**Comment by longbai** [comment]
@dwo yes, processing 2.1 changed it to private

**Comment by dwo** [comment]
@longbai my issue is that I still get that error on the current master, even with using `getSize()`.

**Comment by dwo** [comment]
this is probably because I haven't rebuilt the code_swarm jar, sorry for the trouble.

**Pull request merged**
